"""updated studygroup model

Revision ID: 82b51262f2c3
Revises: a8ef522cd0a6
Create Date: 2025-07-03 15:05:58.779299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b51262f2c3'
down_revision = 'a8ef522cd0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('meeting_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.drop_column('max_members')
        batch_op.drop_column('meeting_time')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
