"""add category, link, privacy to StudyGroup

Revision ID: d8e24d7ee890
Revises: 82b51262f2c3
Create Date: 2025-07-03 15:15:41.574985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e24d7ee890'
down_revision = '82b51262f2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.drop_column('is_private')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
